import "./globals.css";
import AudioPlayer from "@/components/audio/Audio";
import 'bootstrap/dist/css/bootstrap.min.css';
import "@/styles/style.css"
import "@/styles/responsive.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <div className="audioBox">
          <AudioPlayer />
        </div>
        <div className="video-background">
          <video autoPlay loop muted playsInline>
            <source src="/videos/background/bg.mp4" type="video/mp4" />
            Your browser does not support the video tag.
          </video>
          <div className="video-overlay"></div>
          <div className="content">{children}</div>
        </div>
      </body>
    </html>
  );
}
